config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "articles#index"

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible
  
    has_one_attached :image, dependent: :destroy
    has_many :comments, dependent: :destroy
    belongs_to :author, class_name: 'User'
  
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }

    scope :ordered_by_title_asc, -> (direction = :asc) { order(title: direction)}
    scope :ordered_by_title_desc, -> (direction = :desc) { order(title: direction)}
    scope :ordered_by_date_asc, -> (direction = :asc) { order(created_at: direction)}
    scope :ordered_by_date_desc, -> (direction = :desc) { order(created_at: direction)}

    scope :public_articles, -> (status = "public"){ where('status=?',"#{status}")}
    scope :private_articles, -> (status = "private"){ where('status=?',"#{status}")}
    scope :archived_articles, -> (status = "archived"){ where('status=?',"#{status}")}

    scope :with_authors, -> {includes(:author)}
  
  end
  

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end
  
    class_methods do
      def public_count
        where(status: 'public').count
      end
      
      def private_count
        where(status: 'private').count
      end
      
      def archived_count
        where(status: 'archived').count
      end

    end
  
    def archived?
      status == 'archived'
    end
  end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable :rememberable,
  devise :database_authenticatable, :registerable,
         :recoverable,  :validatable
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    include Pundit
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  # http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_article, only: %i[show edit update destroy]
  # before_action :authorize_user!, only: %i[edit update destroy]



  def index

    # @articles = Article.ordered.with_authors.paginate(:page => params[:page], per_page: 5).where('title LIKE ?', "#{params[:search]}%")
    @sort_type = params.fetch(:sort_type, @sort_type)
    @articles = Article.with_authors.paginate(page: params[:page], per_page: 5).where('title LIKE ?', "#{params[:search]}%")
    @status = params.fetch(:status, @status)
    
    if @status == "Public"
      @articles = @articles.public_articles
    elsif @status == "Private"
      @articles = @articles.private_articles
    elsif @status == "Archived"
      @articles = @articles.archived_articles
    end

    if @sort_type == "title_asc"
      @articles = @articles.ordered_by_title_asc
    elsif @sort_type == "title_desc"
      @articles = @articles.ordered_by_title_desc
    elsif @sort_type == "oldest"
      @articles = @articles.ordered_by_date_asc
    else 
      @articles = @articles.ordered_by_date_desc
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.author = current_user

    unless article_params[:image].nil?
      image = Cloudinary::Uploader.upload(article_params[:image], options = {})
    end

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    authorize @article
    @article = Article.find(params[:id])
  end

  def update
    authorize @article
    @article = Article.find(params[:id])
    unless article_params[:image].nil?
      image = Cloudinary::Uploader.upload(article_params[:image], options = {})
    end

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    authorize @article
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status, :image)
    end

    def set_article
      @article = Article.find(params[:id])
    end
  
    def authorize_user!
      return if @article.author_id == current_user.id
      redirect_to :articles, alert: "You are not allowed to make this action!"
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    # http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

    def create
      @article = Article.find(params[:article_id])
      @@comment = @article.comments.create(params[:comment].permit(:body).merge(author_id: current_user.id))
      redirect_to article_path(@article)
    end
  
    def destroy
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      authorize @comment
      @comment.destroy
      redirect_to article_path(@article)
    end

  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
    
    <div style="width:400px; height:auto">
      <%= form.label :title %><br>
      <%= form.text_field(:title, {:class => 'form-control'}) %>
      <% article.errors.full_messages_for(:title).each do |message| %>
        <div class="alert alert-danger"><%= message %></div>
      <% end %>
    </div>
    <br/>
  
    <div style="width:400px; height:auto">
      <%= form.label :body %><br>
      <%= form.text_area(:body, {:class => 'form-control'}) %><br>
      <% article.errors.full_messages_for(:body).each do |message| %>
        <div  class="alert alert-danger"><%= message %></div>
      <% end %>
    </div>

    <div class="field">
      <%= form.label :image %><br>
      <%= form.file_field(:image, {:class => 'rounded'}) %>
    </div>
    <br/>

    <div>
        <%= form.label :status %><br>
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </div>
    <br/>
    <br/>
  
    <div>
      <%= form.submit({:class => 'btn btn-success'}) %>
    </div>
    <br/>
    <br/>

  <% end %>
  

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<br>

<span>This blog has <%= Article.all.count %> articles: <%= Article.public_count %> public, 
        <%= Article.private_count %> private and  <%= Article.archived_count %> archived!</span>
<br>
<br>

<div>
  <span class="font-weight-light">Select status filter:</span>
  <%= link_to "Public", articles_path(status: 'Public'), :class => 'btn btn-info btn-sm' %>
  <%= link_to "Private", articles_path(status: 'Private'), :class => 'btn btn-info btn-sm' %>
  <%= link_to "Archived", articles_path(status: 'Archived'), :class => 'btn btn-info btn-sm' %>
</div>

<div class="mt-2">
  <span class="font-weight-light">Select sorting order:</span>
  <%= link_to "From newest", articles_path(sort_type: 'newest'), :class => 'btn btn-info btn-sm' %>
  <%= link_to "From oldest", articles_path(sort_type: 'oldest'), :class => 'btn btn-info btn-sm' %>
  <%= link_to "From A to Z", articles_path(sort_type: 'title_asc'), :class => 'btn btn-info btn-sm' %>
  <%= link_to "From Z to A", articles_path(sort_type: 'title_desc'), :class => 'btn btn-info btn-sm' %>
</div>


<ul>
  <% @articles.each do |article| %>
    <div class="alert alert-light">
      <li>
        <h4><%= article.title %></h4>
        <%= link_to "Read more...", article, :class => 'btn btn-outline-primary btn-sm' %>
      </li>
    </div>
  <% end %>
</ul>
<%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
<br><br>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<br/>

<p><%= @article.body %></p>

<% if @article.image.present? %>
  <div style="width:400px; height:auto">
    <%= image_tag(@article.image, class:'rounded', style:'width:100%') %>
  </div>
<% end %>
<br>

<% if @article.author.present? %>
<p>
  <em>Article author:</em>
  <em><%= @article.author.username %></em>
</p>
<% end %>
<br>

<% if policy(@article).update? %>
<%= link_to "Edit", edit_article_path(@article), :class => 'btn btn-info' %>
<% end %>
<% if policy(@article).destroy? %>
<%= link_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" },
                  :class => 'btn btn-danger' %>
<% end %>
<br>
<br>

<h4>Comments</h4>
<%= render @article.comments %>
<br/>

<%if user_signed_in? %>
  <h4>Add a comment:</h4>
  <%= render 'comments/form' %>
  <br/>
<% end %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.author.username %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<% if policy(comment).destroy? %>
  <p>
    <%= link_to 'Destroy Comment', [comment.article, comment],
                method: :delete,
                data: { confirm: "Are you sure?" }, :class => 'btn btn-outline-danger btn-sm' %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>

    <div style="width:400px; height:auto">
      <p>
        <%= form.label :body %><br>
        <%= form.text_area(:body, {:class => 'form-control'}) %>
      </p>
    </div>
    <br/>

    <p>
      <%= form.submit({:class => 'btn btn-success'}) %>
    </p>
    <br/>
    <br/>

  <% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NedoICQ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="p-3 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <h5 class="my-0 mr-md-auto font-weight-bold">NedoICQ</h5>
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="../" class="nav-link px-2 text-secondary">Home</a></li>
        <li><a href="/articles/new" class="nav-link px-2 text-white">New Article</a></li>
      </ul>
      
      <%= form_tag(articles_path, method: :get, 
              :class => 'col-12 col-lg-auto mb-6 mb-lg-0 me-lg-6') do %>
        <div class="input-group" style="width:350px">
          <%= text_field_tag(:search, params[:search], 
                :class => 'form-control form-control-dark',
                :placeholder => "Search...", 
                'aria-label' => 'Search',
                'aria-describedby' => 'basic-addon2') %>
          <div class="input-group-append">
            <%= submit_tag("Search", :class => 'btn btn-outline-secondary') %>
          </div>
      </div>
      <% end %> 
      

      <div class="text-end">
        <%if user_signed_in? %>
          <%= current_user.username %>
          <% if current_user.admin? %>
            <span>(admin)</span>
          <% end %>
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, 
                      data: {confirm: 'Are you sure ?'}, :class => 'btn btn-danger me-2' %>
        <% else %>
          <%= link_to 'Login', new_user_session_path, :class => 'btn btn-outline-success me-2' %>
          <%= link_to 'Sign up', "/users/sign_up", :class => 'btn btn-outline-primary' %>
        <% end %>
      </div>
    </div>
  </div>
  </header>
  <br/>

  <%if notice.present? %>
  <p class="alert alert-success" role="alert"><%= notice %></p>
  <% end %>
  <%if alert.present? %>
  <p class="alert alert-danger" role="alert"><%= alert %></p>
  <% end %>
  <br/>

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>